if (!('gpu' in navigator)) {
    navigator.gpu = {
      requestAdapter: () => Promise.resolve({
        name: "AMD Radeon RX 6600",
        vendor: "amd",
        architecture: "gcn-5",
        features: new Set(["texture-compression-bc"]),
        limits: {
          maxTextureDimension1D: 16384,
          maxTextureDimension2D: 16384,
          maxTextureDimension3D: 2048,
          maxTextureArrayLayers: 2048,
          maxBindGroups: 4,
          maxBindGroupsPlusVertexBuffers: 24,
          maxBindingsPerBindGroup: 1000,
          maxDynamicUniformBuffersPerPipelineLayout: 10,
          maxDynamicStorageBuffersPerPipelineLayout: 8,
          maxSampledTexturesPerShaderStage: 16,
          maxSamplersPerShaderStage: 16,
          maxStorageBuffersPerShaderStage: 10,
          maxStorageTexturesPerShaderStage: 8,
          maxUniformBuffersPerShaderStage: 12,
          maxUniformBufferBindingSize: 65536,
          maxStorageBufferBindingSize: 2147483644,
          minUniformBufferOffsetAlignment: 256,
          minStorageBufferOffsetAlignment: 256,
          maxVertexBuffers: 8,
          maxBufferSize: 2147483648,
          maxVertexAttributes: 30,
          maxVertexBufferArrayStride: 2048,
          maxInterStageShaderVariables: 28,
          maxColorAttachments: 8,
          maxColorAttachmentBytesPerSample: 128,
          maxComputeWorkgroupStorageSize: 32768,
          maxComputeInvocationsPerWorkgroup: 1024,
          maxComputeWorkgroupSizeX: 1024,
          maxComputeWorkgroupSizeY: 1024,
          maxComputeWorkgroupSizeZ: 64,
          maxComputeWorkgroupsPerDimension: 65535
        },
        isFallbackAdapter: false,
        requestDevice: () => Promise.resolve({
          label: "",
          features: new Set(["texture-compression-bc"]),
          limits: {
            maxTextureDimension1D: 16384,
            maxTextureDimension2D: 16384,
            maxTextureDimension3D: 2048,
            maxTextureArrayLayers: 2048,
            maxBindGroups: 4,
            maxBindGroupsPlusVertexBuffers: 24,
            maxBindingsPerBindGroup: 1000,
            maxDynamicUniformBuffersPerPipelineLayout: 10,
            maxDynamicStorageBuffersPerPipelineLayout: 8,
            maxSampledTexturesPerShaderStage: 16,
            maxSamplersPerShaderStage: 16,
            maxStorageBuffersPerShaderStage: 10,
            maxStorageTexturesPerShaderStage: 8,
            maxUniformBuffersPerShaderStage: 12,
            maxUniformBufferBindingSize: 65536,
            maxStorageBufferBindingSize: 2147483644,
            minUniformBufferOffsetAlignment: 256,
            minStorageBufferOffsetAlignment: 256,
            maxVertexBuffers: 8,
            maxBufferSize: 2147483648,
            maxVertexAttributes: 30,
            maxVertexBufferArrayStride: 2048,
            maxInterStageShaderVariables: 28,
            maxColorAttachments: 8,
            maxColorAttachmentBytesPerSample: 128,
            maxComputeWorkgroupStorageSize: 32768,
            maxComputeInvocationsPerWorkgroup: 1024,
            maxComputeWorkgroupSizeX: 1024,
            maxComputeWorkgroupSizeY: 1024,
            maxComputeWorkgroupSizeZ: 64,
            maxComputeWorkgroupsPerDimension: 65535
          }
        })
      })
    };
  }
  
  Object.defineProperty(window, 'gpuDeviceLimits', {
    get: () => ({
      maxTextureDimension1D: 16384,
      maxTextureDimension2D: 16384,
      maxTextureDimension3D: 2048,
      maxTextureArrayLayers: 2048,
      maxBindGroups: 4,
      maxBindGroupsPlusVertexBuffers: 24,
      maxBindingsPerBindGroup: 1000,
      maxDynamicUniformBuffersPerPipelineLayout: 10,
      maxDynamicStorageBuffersPerPipelineLayout: 8,
      maxSampledTexturesPerShaderStage: 16,
      maxSamplersPerShaderStage: 16,
      maxStorageBuffersPerShaderStage: 10,
      maxStorageTexturesPerShaderStage: 8,
      maxUniformBuffersPerShaderStage: 12,
      maxUniformBufferBindingSize: 65536,
      maxStorageBufferBindingSize: 2147483644,
      minUniformBufferOffsetAlignment: 256,
      minStorageBufferOffsetAlignment: 256,
      maxVertexBuffers: 8,
      maxBufferSize: 2147483648,
      maxVertexAttributes: 30,
      maxVertexBufferArrayStride: 2048,
      maxInterStageShaderVariables: 28,
      maxColorAttachments: 8,
      maxColorAttachmentBytesPerSample: 128,
      maxComputeWorkgroupStorageSize: 32768,
      maxComputeInvocationsPerWorkgroup: 1024,
      maxComputeWorkgroupSizeX: 1024,
      maxComputeWorkgroupSizeY: 1024,
      maxComputeWorkgroupSizeZ: 64,
      maxComputeWorkgroupsPerDimension: 65535
    })
  });  